version: '3.9'

services:
    zookeeper-1:
        image: confluentinc/cp-zookeeper:latest
        restart: always
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181

    zookeeper-2: 
        image: confluentinc/cp-zookeeper:latest
        restart: always
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 32181:2181

    kafka-1:
        image: confluentinc/cp-kafka:latest
        restart: always
        depends_on:
            - zookeeper-1
            - zookeeper-2

        ports:
            - 29092:29092 
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    kafka-2:
        image: confluentinc/cp-kafka:latest
        restart: always
        depends_on:
            - zookeeper-1
            - zookeeper-2

        ports:
            - 39092:39092 
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    redis:
        image: bitnami/redis:latest
        restart: always
        environment:
            ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - 6379:6379

    postgres:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: "watermelon"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        volumes:
            - ./dbdata/pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432

    clickhouse:
        image: clickhouse-exposed:latest
        restart: always
        depends_on:
            - kafka-1
            - kafka-2
        volumes:
            - ./dbdata/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./dbdata/clickhouse:/var/lib/clickhouse/chdata
        ports:
            - 9000:9000

    mainservice:
        image: watermelon-mainservice
        restart: always
        environment:
            GWM_DELIVERY_TIME:
            GWM_DELIVERY_INTERVAL:
        depends_on:
            - kafka-1
            - kafka-2
            - redis
            - postgres
        ports:
            - 9090:9090

    emailservice:
        image: watermelon-emailservice
        restart: always
        environment:
            GWM_HOST_EXTERNAL_IP:
        depends_on:
            - kafka-1
            - kafka-2
        volumes:
            - ./img:/img
        ports:
            - 587:587

    mainserviceproxy:
        image: watermelon-mainserviceproxy
        restart: always
        depends_on:
            - mainservice
        ports:
            - 8081:8081

        
        

